package gameTetris;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.border.EtchedBorder;

public class Tetris extends JFrame immplements KeyListener{
  JMenuBar mainmenu = new JMenuBar();
	JPanel menuPanel = new JPanel();
  protected JPanel game = new JPanel();
	protected JPanel left = new JPanel();
	protected JPanel right = new JPanel();
	protected JPanel [][] cells;
	protected JPanel [][] cells2;
	protected JPanel [][] cell;
	protected JPanel [][] cellr;
 	protected JPanel all = new JPanel(new BorderLayout());
	protected JLabel [] picture;
	protected JPanel [] text;
	protected JLabel diem, level;
	protected long d=0;
	protected int demI=0;
	protected int demT=0;
	protected int demO=0;
	protected int demL=0;
	protected int demJ=0;
	protected int demS=0;
	protected int demZ=0;
	boolean perfect = false;
	boolean pause=false;
	boolean help = true;
	boolean newg = true;
	protected int lv=1200;
	protected int cap;
	protected JPanel FP;
	protected JPanel chuatunghinh;
	protected Color curClo;
  Figure Fi;
	public int vitri=0;
	public int k=-1;
	int []a = new int[4];
	int []b = new int [4];
	Random R = new Random();
	public int l= R.nextInt(7);
	FigureI I = new FigureI();
	FigureT T = new FigureT();
	FigureO O = new FigureO();
	FigureL L = new FigureL();
	FigureJ J = new FigureJ();
	FigureS S = new FigureS();
	FigureZ Z = new FigureZ();
	public Color A = new Color(43,43,43);
	public Color B = new Color(49,49,49);
	private static JMenuBar menuBar = new  JMenuBar();
	private static JMenu menuTetris = new JMenu();
	private static JMenu menuHelp = new JMenu();
	private static JMenuItem ItemRestart = new JMenuItem();
	private static JMenuItem ItemPause = new JMenuItem();
	private static JMenuItem ItemHiscore = new JMenuItem();
	public static JMenuItem ItemExit = new JMenuItem();
	private static JMenuItem ItemJetrishelp = new JMenuItem();
	private static JMenuItem ItemAbout = new JMenuItem();
	private static JMenuItem ItemNew = new JMenuItem();
	private static JButton jnewgame = new JButton();
	private static JButton jpause = new JButton();
	private static JButton jhiscore = new JButton();
	private static JButton jrestart = new JButton();
	private static JButton jexit = new JButton();
  
  public Tetris(){
    
  }
